### PR TITLE
Add a WS2812 SPI blinky example for the BBC micro:bit v2

### PR DESCRIPTION
**Pull request by jwillikers**

### CODE REVIEW

**Comment by david-sawatzke** [comment]
Looks good, thank you!

**Comment by flapjackfritz** [comment]
I've been giving this script a try with my microbit v2. It seems to build and flash alright, but it doesn't seem to work at all or do anything at all to my WS2812b strip when I connect it up. Everything seems to be working alright though, just no response what so ever from the lights. Any resources or places I can read up to get some better idea how this works, or suggestions I can try out to see if I can trouble shoot it?

**Comment by jwillikers** [comment]
> I've been giving this script a try with my microbit v2. It seems to build and flash alright, but it doesn't seem to work at all or do anything at all to my WS2812b strip when I connect it up. Everything seems to be working alright though, just no response what so ever from the lights. Any resources or places I can read up to get some better idea how this works, or suggestions I can try out to see if I can trouble shoot it?

@flapjackfritz Checkout the README for the `ws2812-spi-rs` package, which has a [troubleshooting section](https://github.com/smart-leds-rs/ws2812-spi-rs#it-doesnt-work). Make sure you're connecting the SPI MOSI pin #15 to DIN on the WS2812 strip, and that your level-shifting the microcontroller's 3.3V output up to 5V if you are powering the NeoPixels with a separate 5V supply. 

There is also a Matrix chat room available for the smart-leds project: https://matrix.to/#/#smart-leds-rs_community:gitter.im

**Comment by jwillikers** [comment]
@flapjackfritz This is going to seem absurd, but what happens when you edit the `.cargo/config` file and use two spaces instead of four spaces before the first rustflags element?

So the original file:

```toml
rustflags = [
    "-C", "link-arg=-Tlink.x",
]
```

Should now look like this:

```toml
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
```

**Comment by jwillikers** [comment]
@flapjackfritz I think this is actually due to a timing issue. Turning up the SPI clock fixed my issues. Try turning up the SPI frequence to `spi::Frequency::M4`.

```rust
let spi = spi::Spi::new(dp.SPI0, pins, spi::Frequency::M4, spi::MODE_0);
```

**Comment by flapjackfritz** [comment]
I think I'm incorrectly using the microbit. I'm not doing any power shifting, though I do have a 5v power supply I'm feeding into the +voltage of the light strip. How do I level-shift it to 5v?

**Comment by jwillikers** [comment]
> I think I'm incorrectly using the microbit. I'm not doing any power shifting, though I do have a 5v power supply I'm feeding into the +voltage of the light strip. How do I level-shift it to 5v?

@flapjackfritz I use a level shifter, the [74AHCT125](https://www.adafruit.com/product/1787) which you can get from a lot of electronic suppliers. You feed it your data signal from the MCU and it level-shifts it up from 3.3V to 5V. Generally, the datasheets for level-shifters are pretty straightforward, but there's also a good video [here](https://www.youtube.com/watch?v=y6HiDnyhRa0), too.

**Pull request merged**
