### PR TITLE
Add a Raspberry Pi Pico WS2812 SPI RGBW blinky example

### PR DESCRIPTION
**Pull request by jwillikers**

### CODE REVIEW

**Review by david-sawatzke — CHANGES_REQUESTED** [review]
Looks good, thank you for the great readme!

A few suggestions:

- `arm-none-eabi-gcc` & `arm-none-eabi-newlib` are also dependencies, due to rp2040-boot2 (no idea how I didn't have them installed).

- Clarify readme to only install `probe-run-rp` when necessary

- Might make more sense to use https://github.com/majbthrd/pico-debug for debugging, as it works with only one board (and works for this code)

- The DELAY interval is set so low that you can't see anything. Should probably be a second

- `--release` mode probably makes more sense

If you disagree with some point, I'm also happy to merge this as-is.

**Comment by jwillikers** [comment]
I'll update the README to use `pico-debug` since that's a simpler solution for debugging. Asid from that, everything else should be taken care of.

**Comment by jwillikers** [comment]
Wow, `pico-debug` is great. Thanks for bringing that up. How's everything look now? I included the instructions for installing the system packages for both Ubuntu and Fedora Linux for the GNU Arm Embedded Toolchain, though perhaps that's tailoring to Linux users. Just let me know if you want anything else changed.

**Comment by david-sawatzke** [comment]
LGTM!

**Pull request merged**
